name: ssh command
on:
  push:
    branches:
      - main
jobs:
  test_and_deploy_to_staging:
    runs-on: ubuntu-latest
    steps:
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.DEV_SSH_HOST }}
          SSH_PORT: ${{ secrets.DEV_SSH_PORT }}
          SSH_USER: ${{ secrets.DEV_SSH_USER }}
          SSH_KEY: ${{ secrets.DEV_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }} bash /app/deploy.sh ayumi_otake

  deploy_to_production:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Production Server
        id: ssh_production
        uses: invi5H/ssh-action@v1
        with:
          SSH_HOST: ${{ secrets.PRODUCTION_SSH_HOST }}
          SSH_PORT: ${{ secrets.PRODUCTION_SSH_PORT }}
          SSH_USER: ${{ secrets.PRODUCTION_SSH_USER }}
          SSH_KEY: ${{ secrets.PRODUCTION_SSHE_SSH_KEY }}
      - run: ssh ${{ steps.ssh_production.outputs.SERVER }} bash /app/deploy.sh ayumi_otake


