name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up SSH key for Staging
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEV_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Run Cypress tests #サイプレステスト実施
      run: |
        cd /ci/
        npx cypress run --browser chrome --spec cypress/e2e/ayumi_otake.*

    - name: Set up SSH key for Production
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519

    - name: Deploy to Production
      run: |
        ssh -i ~/.ssh/id_ed25519 ${{ secrets.PRODUCTION_SSH_USER }}@${{ secrets.PRODUCTION_SSH_HOST }} "bash /app/deploy.sh ayumi_otake"
